name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      
      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
          echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash          

      - name: Check out source code
        uses: actions/checkout@v1

      - name: echo env
        run: |
          echo $(go env GOPATH)
          echo $(go env GOROOT)
          echo $PATH

      - name: go get
        run: go get -v -u github.com/xandronus/goxds/src

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build ./src/goxds.go

  release-windows:
    name: release windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: windows