name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      
      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
          echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash          

      - name: Check out source code
        uses: actions/checkout@v1

      - name: echo env
        run: |
          echo $(go env GOPATH)
          echo $(go env GOROOT)
          echo $PATH

      - name: go get
        run: go get -v -u ./...   

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build ./src/goxds.go